### ISSUE TITLE
[Typo Fix] "baseUrl" in Readme.md , but baseURL used in source codes

### ISSUE THREAD

**Issue by Kane-Kuroneko** [momocow/webpack-userscript#110]
I wrote `'baseUrl:http://127.0.0.1:12345'` in webpack.config.js as the document specified, but the code generated 'localhost:8080'. I discovered the typo by searching for keywords.
Thanks you for this great project !
![image](https://github.com/user-attachments/assets/74388855-2872-4211-a6b2-e7d414056272)
![image](https://github.com/user-attachments/assets/e871913a-4c06-4059-93fc-b4a877ba4d33)

**Comment by momocow** [comment]
Thank you for pointing out the typo.
