### ISSUE TITLE
Add support for @noframes

### ISSUE THREAD

**Issue by rafaelgssa** [momocow/webpack-userscript#24]
@noframes takes no arguments, so it's removed because the headers object is passed through the `trimFalsyLeaves` function.

**Comment by momocow** [comment]
According to #22 it seems that the format of `HeaderObject` is not sufficient enough for all the requirements (currently `@webRequest` and `@noframes`). I may start a rework by this weekend.

**Comment by momocow** [comment]
@rafaelgssa Now you can set `noframes` to `true` in the header object to generate a `@noframes` header without a value.

**Comment by rafaelgssa** [comment]
Nice, thanks!
