### ISSUE TITLE
How to use this plugin only for certain webpack entries?

### ISSUE THREAD

**Issue by Buntelrus** [momocow/webpack-userscript#36]
I have a userscript with pdf.js as a dependency. And for that I need an extra entry for a worker file.

```
entry: {
    main: "./app/index.js",
    "pdf.worker": "pdfjs-dist/build/pdf.worker.entry",
  }
```

If I build the project, I get 2 files:
```
main.bundle.user.js
pdf.worker.bundle.user.js`
```

But what I want is 1 user script `main.bundle.user.js` and 1 normal bundle `pdf.worker.bundle.js`. Is this possible? How can I do this?

**Comment by momocow** [comment]
You can try to build those files via multiple configuration objects.

https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations

**Comment by Buntelrus** [comment]
thanks for the answer. I will try that :)

**Comment by momocow** [comment]
I'll close this issue now but feel free to reopen it if there is further question.

**Comment by iamogbz** [comment]
@momocow how would I get this to work with code splitting? Currently all my chunks get appended with `.user.js` when I only want it for the specified entries. Use case is sharing library code between entry userscripts.

**Comment by momocow** [comment]
@iamogbz I've created a new issue #41 for discussion. Maybe provide a simplified concrete example for me to better understand your requirements.

**Comment by momocow** [comment]
I'll reopen this issue since there are some changes in the incoming v3 which can improve the solution of this issue.
