### ISSUE TITLE
Plugin throws error when package.json is not in context directory

### ISSUE THREAD

**Issue by StrikeAgainst** [momocow/webpack-userscript#47]
I'm having a case where I'm running webpack in a context directory descendant to my project directory, i.e. the package.json is not in the same directory. This leads to an error, where the process is not able to read a package.json from the same directory.

Would it be viable to implement that you can register the package.json path for the plugin explicitly in an option field, and/or, if the file can't be found, have the package data values default to empty as it already does with missing package properties?

**Comment by momocow** [comment]
Hi, thanks for reporting the issue.

Since the package.json is required only for default values of headers, you are right that empty values should be provided if the file cannot be found.

The fix will be included in the next patch version.
