### ISSUE TITLE
Exclude updateUrl/downloadUrl in proxy userscript

### ISSUE THREAD

**Issue by notme1560** [momocow/webpack-userscript#55]
When I generate the proxy userscript, it has the `@downloadURL` and `@updateURL` in the header from `downloadBaseUrl` and `updateBaseUrl` in the plugin settings. Sometimes my userscript manager will update the proxy script from the updateurl and I have to downgrade the proxy script by opening it in the browser again so that it's empty with a `@require` instead. 

Is there a way to stop the proxy script from generating with these headers?

**Comment by momocow** [comment]
Fixed by #56
