### ISSUE TITLE
[feature] Export `HeadersProvider` at top level

### ISSUE THREAD

**Issue by vitoyucepi** [momocow/webpack-userscript#85]
## Summary
I'd like to add type for a standalone function.

Here's how I can do it now
```ts
import WebpackUserscript from 'webpack-userscript';
import {HeadersProvider} from 'webpack-userscript/dist/features';

const userScriptHeadersProvider: HeadersProvider = (headers) => {
  console.log(headers);
  headers.version += '-test'
  return headers;
};

const plugin = new WebpackUserscript({headers: userScriptHeadersProvider});
```

## Versions

Webpack: *5.76.0*
Webpack-userscript: *3.0.1*

## Additional
Maybe it'll be a good idea to move `HeadersProvider` to `types.ts`?
https://github.com/momocow/webpack-userscript/blob/96cf022227ba5e306628334a7477743bb22351d4/lib/features/load-headers.ts#L14-L17

**Comment by momocow** [comment]
> Maybe it'll be a good idea to move `HeadersProvider` to `types.ts`?

Nope, it should be in the place where it is consumed to keep the modularity. The `load-headers` feature is responsible for defining how it looks like.

I'll re-export it in the `types.ts` instead of moving it, along with other options-related types.
