### ISSUE TITLE
webpack error when output filename ends with ".user.js"

### ISSUE THREAD

**Issue by RudeySH** [momocow/webpack-userscript#90]
After updating to webpack-userscript v3.0.0+, I get the following error when I run webpack:

> ERROR in Conflict: Multiple assets emit different content to the same filename exampe.user.js

This is my webpack.config.js:

```js
const path = require('path');
const { UserscriptPlugin } = require('webpack-userscript');

module.exports = {
  entry: './example.js',
  output: {
    filename: 'example.user.js',
    path: path.resolve(__dirname, 'dist'),
  },
  plugins: [
    new UserscriptPlugin(),
  ],
};
```

**Solution:** I was able to fix the error by changing the filename to `'example.js'`, removing the ".user" part.

This is a breaking change compared to v2.5.8.

I doubt causing a webpack error is intended, but I'm unsure if this needs to be fixed. The main reason I'm creating this issue is so others who run into this error, find the solution here.

**Comment by momocow** [comment]
This is a bug.

The purpose of this behavior is to ensure the filename to be ended with `.user.js`, not to prevent users from explicitly specifying the file extension.

I'll fix it soon.

**Comment by MisterRee** [comment]
Any update on this @momocow? I've had to roll back to 2.5.8 pending the fix here.

**Comment by mjpieters** [comment]
> Any update on this @momocow? I've had to roll back to 2.5.8 pending the fix here.

Just set your output filename to use .js instead of user.js for now:

```
    output: {
      clean: true,
      path: OUTPUT,
      // Can't use [name].user.js, see momocow/webpack-userscript#90
      filename: '[name].js',
    },
```

See [my project `webpack.conf.ts`](https://github.com/mjpieters/SO-userscripts/blob/main/webpack.config.ts).
